//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICSE_Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ELEMENTO()
        {
            this.ENTRADA = new HashSet<ENTRADA>();
        }
    
        public int id_elem { get; set; }
        public string elem_ref { get; set; }
        public string elem_nom { get; set; }
        public Nullable<int> categoria { get; set; }
        public Nullable<int> Proveedor { get; set; }
    
        public virtual CATEGORIA CATEGORIA1 { get; set; }
        public virtual PROVEEDOR PROVEEDOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADA> ENTRADA { get; set; }
    }
}
