//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICSE_Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADA_SOLICITUD
    {
        public int id { get; set; }
        public Nullable<int> entrada { get; set; }
        public Nullable<int> solicitud { get; set; }
        public Nullable<int> cant { get; set; }
    
        public virtual ENTRADA ENTRADA1 { get; set; }
        public virtual SOLICITUD SOLICITUD1 { get; set; }
    }
}
