//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICSE_Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_entrada
    {
        public int id_registro { get; set; }
        public string elem_ref { get; set; }
        public string elem_nom { get; set; }
        public Nullable<int> cant { get; set; }
        public System.DateTime fecha { get; set; }
        public string usu_nombre { get; set; }
    }
}
