//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICSE_Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD()
        {
            this.ENTRADA_SOLICITUD = new HashSet<ENTRADA_SOLICITUD>();
        }
        /*Nullable<System.DateTime> */
        public int id_solicitud { get; set; }
        public Nullable<DateTime> sol_fecha { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<System.DateTime> fecha_progra { get; set; }
        public string solicitante { get; set; }
        public Nullable<int> sede { get; set; }
        public Nullable<int> tecnico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADA_SOLICITUD> ENTRADA_SOLICITUD { get; set; }
        public virtual SEDE SEDE1 { get; set; }
        public virtual TECNICO TECNICO1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
